"""Adicionando tabelas Tbcarrinho e Tbvinhosdocarrinho

Revision ID: 42f17623cc64
Revises: d0d75dcc6ab8
Create Date: 2023-11-29 00:03:55.216637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f17623cc64'
down_revision: Union[str, None] = 'd0d75dcc6ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbvinhosdocarrinho',
    sa.Column('pkcodigovincar', sa.Integer(), nullable=False),
    sa.Column('fkcodigovin', sa.Integer(), nullable=True),
    sa.Column('fkcodigocar', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fkcodigocar'], ['tbcarrinho.pkcodigocar'], ),
    sa.ForeignKeyConstraint(['fkcodigovin'], ['tbvinho.pkcodigovin'], ),
    sa.PrimaryKeyConstraint('pkcodigovincar')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbvinhosdocarrinho')
    # ### end Alembic commands ###
