"""create initial tables

Revision ID: 940a07de88bd
Revises: def4c931deef
Create Date: 2023-11-28 21:16:02.495557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '940a07de88bd'
down_revision: Union[str, None] = 'def4c931deef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbcarrinho',
    sa.Column('pkcodigocar', sa.Integer(), nullable=False),
    sa.Column('estadocar', sa.String(length=20), nullable=False),
    sa.Column('fkcodigocli', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fkcodigocli'], ['tbcliente.pkcodigocli'], ),
    sa.PrimaryKeyConstraint('pkcodigocar')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbcarrinho')
    # ### end Alembic commands ###
