"""create initial tables

Revision ID: def4c931deef
Revises: 
Create Date: 2023-11-27 00:09:09.411436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'def4c931deef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbcategoria',
    sa.Column('pkcodigocat', sa.Integer(), nullable=False),
    sa.Column('nomecat', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('pkcodigocat')
    )
    op.create_table('tbtipo',
    sa.Column('pkcodigotip', sa.Integer(), nullable=False),
    sa.Column('nometip', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('pkcodigotip')
    )
    op.create_table('tbvinho',
    sa.Column('pkcodigovin', sa.Integer(), nullable=False),
    sa.Column('nomevin', sa.String(length=50), nullable=False),
    sa.Column('precovin', sa.Float(), nullable=False),
    sa.Column('anovin', sa.Integer(), nullable=False),
    sa.Column('paisvin', sa.String(length=50), nullable=False),
    sa.Column('estoquevin', sa.Integer(), nullable=True),
    sa.Column('fkcodigotip', sa.Integer(), nullable=True),
    sa.Column('fkcodigocat', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fkcodigocat'], ['tbcategoria.pkcodigocat'], ),
    sa.ForeignKeyConstraint(['fkcodigotip'], ['tbtipo.pkcodigotip'], ),
    sa.PrimaryKeyConstraint('pkcodigovin')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbvinho')
    op.drop_table('tbtipo')
    op.drop_table('tbcategoria')
    # ### end Alembic commands ###
